name: Source Build
on:
  pull_request:  # just for testing
  push:
    branches:
      - master
  schedule:
    # Run every day to detect flakiness and broken dependencies
    - cron: '43 3 * * *'

jobs:
  source:
    name: source build
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
    steps:
      - uses: ros-tooling/setup-ros@v0.2
      - uses: ros-tooling/action-ros-ci@v0.2
        with:
          target-ros2-distro: rolling
          # build all packages listed in the meta package
          package-name:
            smacc2
            # smacc_client_library
            keyboard_client
            move_base_z_client
            multirole_sensor_client
            ros_publisher_client
            ros_timer_client
            # smacc_event_generators
            eg_conditional_generator
            eg_random_generator
            #
            smacc_msgs
            # smacc_sm_reference_library
            sm_atomic
            sm_atomic_performance_test
            sm_atomic_subscribers_performance_test
            sm_dance_bot
            sm_dance_bot_msgs
            sm_dance_bot_strikes_back
            sm_ferrari
            sm_three_some
            # smacc_state_reactor_library
            sr_all_events_go
            sr_conditional
            sr_event_countdown
          vcs-repo-file-url: |
            https://raw.githubusercontent.com/ros2/ros2/master/ros2.repos
            https://raw.githubusercontent.com/${{ github.repository }}/${{ github.sha }}/smacc2.repos
          colcon-mixin-repository: https://raw.githubusercontent.com/colcon/colcon-mixin-repository/master/index.yaml
      - uses: actions/upload-artifact@v1
        with:
          name: colcon-logs-${{ matrix.os }}
          path: ros_ws/log
