jobs:
  pre-commit:
    name: Format
    runs-on: ubuntu-latest
    container: 
      image: ros/humble-desktop:latest
      
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2

    - name: Install clang-format
      run: |
       sudo apt-get update
       sudo apt-get install -y clang-format cppcheck
       git config --global --add safe.directory `pwd`
       pip3 install pre-commit
    - name: "pre-commit"
      run: |
        source /opt/ros/humble/setup.bash
        echo `pwd`
        pre-commit run -a