name: Humble Semi-Binary Build (main)
# author: Denis Štogl <denis@stoglrobotics.de>
# description: 'Build & test all dependencies from released (binary) packages.'

on:
  pull_request:
    branches:
      - humble
  push:
    branches:
      - humble
  schedule:
    # Run every morning to detect flakiness and broken dependencies
    - cron: '03 3 * * *'

jobs:
  binary:
    runs-on: ubuntu-22.04
    container:
      image: osrf/ros:humble-desktop
  
    steps:
      - run: |
          apt-get update
     
      - uses: ./.github/workflows/reusable-industrial-ci-with-cache.yml
        with:
          ros_repo: main
          ros_distro: humble
          upstream_workspace: SMACC2.humble.repos
          ref_for_scheduled_build: humble
